language: python
python:
  - 3.3
  - 3.4
  - 3.5

sudo: required

install:
  - pip install pep8
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pep8 isperdal tests examples setup.py
  - nosetests --with-doctest -s -v
